### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by LJJcodeing** [heleidsn/px4_avoidance_airsim#1]
Is there a video tutorial available? Or a more detailed configuration document. I want to try reproducing it. Grateful without hesitation

**Comment by heleidsn** [comment]
Hi! 

Unfortunately, there is no video tutorial for this repo. 

You can try to run it on your machine and open issues with the problems.

Best

**Comment by LJJcodeing** [comment]
Okay, let me give it a try. thanks
